In [1]:
import pandas as pd

# Load the CSV file into a DataFrame
file_path = "C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv"
df = pd.read_csv(file_path)

# Display the data types of each column
print(df.dtypes)

_id                        int64
listing_url               object
name                      object
summary                   object
space                     object
description               object
neighborhood_overview     object
notes                     object
transit                   object
access                    object
interaction               object
house_rules               object
property_type             object
room_type                 object
bed_type                  object
minimum_nights             int64
maximum_nights             int64
cancellation_policy       object
last_scraped              object
calendar_last_scraped     object
accommodates               int64
bedrooms                 float64
beds                     float64
number_of_reviews          int64
bathrooms                float64
amenities                 object
price                    float64
extra_people             float64
guests_included            int64
images                    object
host                      object
address                   object
availability              object
review_scores             object
reviews                   object
first_review              object
last_review               object
security_deposit         float64
cleaning_fee             float64
weekly_price             float64
monthly_price            float64
reviews_per_month        float64
dtype: object

In [4]:
import pandas as pd

# Assuming your data is loaded into a DataFrame named 'df'

# Function to extract coordinates from the nested dictionary (handles various input types)
def get_coordinates(address_dict):
  # Check if 'address_dict' is a dictionary (expected case)
  if isinstance(address_dict, dict):
    # Existing logic for handling nested dictionary structure
    if "location" in address_dict and isinstance(address_dict["location"], dict):
      coordinates = address_dict["location"].get("coordinates")
      if coordinates:
        return coordinates[0], coordinates[1]
  # Handle cases where 'address_dict' is not a dictionary (might be missing or different format)
  return None, None  # Return None values if coordinates are unavailable

# Apply the function to 'address' column and create new columns (handles potential errors)
try:
  df["latitude"], df["longitude"] = df["address"].apply(get_coordinates).unzip()
except AttributeError:  # Handle potential errors during apply
  print("Error encountered while extracting coordinates. Check data consistency.")

# Now you can use 'df["latitude"]' and 'df["longitude"]' for geospatial visualization (if extraction successful)

Error encountered while extracting coordinates. Check data consistency.

In [5]:
df["address"].head()

0    {'street': 'Montréal, Québec, Canada', 'suburb...
1    {'street': 'Brooklyn, NY, United States', 'sub...
2    {'street': 'Porto, Porto, Portugal', 'suburb':...
3    {'street': 'Hong Kong, Hong Kong Island, Hong ...
4    {'street': 'Montréal, Québec, Canada', 'suburb...
Name: address, dtype: object

In [6]:
df["address"].dtypes

dtype('O')

In [11]:
inconsistent_rows = df[df["address"].isna()]
inconsistent_rows

Empty DataFrame
Columns: [_id, listing_url, name, summary, space, description, neighborhood_overview, notes, transit, access, interaction, house_rules, property_type, room_type, bed_type, minimum_nights, maximum_nights, cancellation_policy, last_scraped, calendar_last_scraped, accommodates, bedrooms, beds, number_of_reviews, bathrooms, amenities, price, extra_people, guests_included, images, host, address, availability, review_scores, reviews, first_review, last_review, security_deposit, cleaning_fee, weekly_price, monthly_price, reviews_per_month]
Index: []

[0 rows x 42 columns]

In [13]:
# Identify rows where 'location' is missing or not a dictionary
inconsistent_rows = df[~df["address"].apply(lambda x: isinstance(x, dict) and x.get("location") is not None)]

inconsistent_rows

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,availability,review_scores,reviews,first_review,last_review,security_deposit,cleaning_fee,weekly_price,monthly_price,reviews_per_month
0,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,"Prime location, amazing lighting and no annoyi...",Lot's of plants and lights. Really great mode...,"Prime location, amazing lighting and no annoyi...",NaN,NaN,NaN,NaN,...,"{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10057826,https://www.airbnb.com/rooms/10057826,Deluxe Loft Suite,Loft Suite Deluxe @ Henry Norman Hotel Located...,This loft unit features a kitchenette and is f...,Loft Suite Deluxe @ Henry Norman Hotel Located...,Greenpoint is an artsy Brooklyn neighborhood f...,NaN,NaN,"Guest will have access to common terraces, lou...",...,"{'availability_30': 30, 'availability_60': 31,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58665374', 'date': datetime.datetime...",2016-01-03 05:00:00,2018-02-18 05:00:00,NaN,NaN,NaN,NaN,NaN
2,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,"{'availability_30': 28, 'availability_60': 47,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58663741', 'date': datetime.datetime...",2016-01-03 05:00:00,2019-01-20 05:00:00,200.0,35.0,NaN,NaN,NaN
3,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,"Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,NaN,NaN,NaN,...,"{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '56904633', 'date': datetime.datetime...",2015-12-19 05:00:00,2018-03-27 04:00:00,NaN,NaN,5000.0,NaN,NaN
4,10066928,https://www.airbnb.com/rooms/10066928,3 chambres au coeur du Plateau,Notre appartement comporte 3 chambres avec cha...,"Notre logement est lumineux, plein de vie et c...",Notre appartement comporte 3 chambres avec cha...,"L'appartement se situe au coeur du Plateau, do...",NaN,L'appartement se situe à égale distance des mé...,Le logement sera disponible en entier pour vot...,...,"{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9738789,https://www.airbnb.com/rooms/9738789,Pittwater - designer home & pool,Beautiful modern architect designed home - 4 b...,"Modern 4 bedroom, 2.5 bathroom open plan house...",Beautiful modern architect designed home - 4 b...,Quite street with 100 metre walk to Pittwater ...,NaN,Bus stop 100 metres away on main road - Pittwa...,Access to house and garden (not garages).,...,"{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,500.0,NaN,2500.0,NaN,NaN
5551,9895628,https://www.airbnb.com/rooms/9895628,Duplex com vista para o J. Botanico,O apartamento é amplo e localizado em rua tran...,O apartamento fica em prédio antigo e é muito ...,O apartamento é amplo e localizado em rua tran...,A rua tem restaurantes e lojas descoladas e de...,"Temos 2 suites com cama de casal, um sofá cama...",NaN,Muito silencioso e iluminado. A cozinha é perf...,...,"{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '94452416', 'date': datetime.datetime...",2016-08-15 04:00:00,2016-08-15 04:00:00,800.0,200.0,NaN,NaN,NaN
5552,9907103,https://www.airbnb.com/rooms/9907103,Brand New Luxury Downtown Studio,Perfectly located on the very famous Crescent ...,Perfectly located on the very famous Crescent ...,Perfectly located on the very famous Crescent ...,NaN,NaN,NaN,NaN,...,"{'availability_30': 29, 'availability_60': 59,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '57825526', 'date': datetime.datetime...",2015-12-29 05:00:00,2017-01-06 05:00:00,NaN,50.0,NaN,NaN,NaN
5553,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,NaN,NaN,NaN,...,"{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9951865,https://www.airbnb.com/rooms/9951865,Quarto Legal,"Meu espaço é perto de Cristo Redentor, Copacab...","Sala, cozinha, áreas comuns do prédio. Caso o ...","Meu espaço é perto de Cristo Redentor, Copacab...","Gosto de morar aqui, e tranquilo ,tem acesso a...",No nossa condomínio possuímos sala de jogos sê...,"Os hóspedes podem se locomover de ônibus, metr...","Podem usar a sala , cozinha , banheiro e a aca...",...,"{'availability_30': 30, 'availability_60': 60,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '235088123', 'date': datetime.datetim...",2018-02-15 05:00:00,2018-02-15 05:00:00,0.0,50.0,NaN,NaN,NaN

In [15]:
!pip install geopy

Collecting geopy
  Obtaining dependency information for geopy from https://files.pythonhosted.org/packages/e5/15/cf2a69ade4b194aa524ac75112d5caac37414b20a3a03e6865dfe0bd1539/geopy-2.4.1-py3-none-any.whl.metadata
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Obtaining dependency information for geographiclib<3,>=1.52 from https://files.pythonhosted.org/packages/9f/5a/a26132406f1f40cf51ea349a5f11b0a46cec02a2031ff82e391c2537247a/geographiclib-2.0-py3-none-any.whl.metadata
  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   --------- ----------------------------- 30.7/125.4 kB 445.2 kB/s eta 0:00:01
   ------------------- ------------------- 61.4/125.4 kB 550.5 kB/s eta 0:00:01
   -------------------------------------- 125.4/125.4 kB 822.8 kB/s eta 0:00:00
Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
   ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
   ---------------------------------------- 40.3/40.3 kB ? eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.1

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import pandas as pd
from geopy.geocoders import Nominatim

# Assuming your data is loaded into a DataFrame named 'df'

# Function to extract coordinates from the address (handles dictionaries and strings)
def get_coordinates(address):
  # Check if 'address' is a dictionary (expected case)
  if isinstance(address, dict):
    # Existing logic for handling nested dictionary structure
    if "location" in address and isinstance(address["location"], dict):
      coordinates = address["location"].get("coordinates")
      if coordinates:
        return coordinates[0], coordinates[1]
  # Handle strings (consider one of the options below)
  else:
    # Option 1: Ignore string addresses (assuming no coordinates)
    return None, None

    # Option 2: Extract coordinates from strings (advanced)
    # This requires modifying the code based on your specific string format
    # For example, if latitude and longitude are separated by a comma:
    #  try:
    #    lat, lon = address.split(",")
    #    return float(lat), float(lon)
    #  except ValueError:
    #    return None, None

# Create a Nominatim geocoder object (optional, for error handling)
geolocator = Nominatim(user_agent="myGeocoder")

# Apply the function to 'address' column and create new columns (handles potential errors)
try:
  df["latitude"], df["longitude"] = df["address"].apply(get_coordinates).unzip()
except AttributeError:  # Handle potential errors during apply
  print("Error encountered while extracting coordinates. Check data consistency.")

# Handle potential Geocoder errors (consider adding this within the 'try' block)
except Exception as e:
  print(f"Error using Nominatim geocoder: {e}")
  # Handle the error (e.g., retry with a delay, log the error)

# Now you can use 'df["latitude"]' and 'df["longitude"]' for geospatial visualization

Error encountered while extracting coordinates. Check data consistency.

In [19]:
import pandas as pd

# Load the dataset
file_path = "C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv"
df = pd.read_csv(file_path)

# Convert string representations of dictionaries in 'address' column to actual dictionaries
df['address'] = df['address'].apply(eval)

# Extract latitude and longitude coordinates from the 'address' column
df['latitude'] = df['address'].apply(lambda x: x['location']['coordinates'][1] if 'location' in x else None)
df['longitude'] = df['address'].apply(lambda x: x['location']['coordinates'][0] if 'location' in x else None)

print(df["latitude"].dtypes)
print(df["longitude"].dtypes)

# Display the dataframe with latitude and longitude columns
print(df[['latitude', 'longitude']])

float64
float64
       latitude   longitude
0     45.518890  -73.591110
1     40.727780  -73.944720
2     41.141300   -8.613080
3     22.281580  114.150270
4     45.522330  -73.573830
...         ...         ...
5550 -33.651980  151.287260
5551 -22.963607  -43.220452
5552  45.496630  -73.576390
5553 -22.908336  -43.173761
5554 -22.918155  -43.210667

[5555 rows x 2 columns]

In [20]:
df.dtypes

_id                        int64
listing_url               object
name                      object
summary                   object
space                     object
description               object
neighborhood_overview     object
notes                     object
transit                   object
access                    object
interaction               object
house_rules               object
property_type             object
room_type                 object
bed_type                  object
minimum_nights             int64
maximum_nights             int64
cancellation_policy       object
last_scraped              object
calendar_last_scraped     object
accommodates               int64
bedrooms                 float64
beds                     float64
number_of_reviews          int64
bathrooms                float64
amenities                 object
price                    float64
extra_people             float64
guests_included            int64
images                    object
host                      object
address                   object
availability              object
review_scores             object
reviews                   object
first_review              object
last_review               object
security_deposit         float64
cleaning_fee             float64
weekly_price             float64
monthly_price            float64
reviews_per_month        float64
latitude                 float64
longitude                float64
dtype: object

In [2]:
df.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'accommodates', 'bedrooms',
       'beds', 'number_of_reviews', 'bathrooms', 'amenities', 'price',
       'extra_people', 'guests_included', 'images', 'host', 'address',
       'availability', 'review_scores', 'reviews', 'first_review',
       'last_review', 'security_deposit', 'cleaning_fee', 'weekly_price',
       'monthly_price', 'reviews_per_month'],
      dtype='object')

In [3]:
import json

# Sample JSON availability string
availability_json = "{'availability_30': 28, 'availability_60': 47, 'availability_90': 74, 'availability_365': 239}"

# Parse the JSON string into a Python dictionary
availability_dict = json.loads(availability_json.replace("'", "\""))

# Extract the values of different availabilities
availability_30 = availability_dict.get('availability_30', None)
availability_60 = availability_dict.get('availability_60', None)
availability_90 = availability_dict.get('availability_90', None)
availability_365 = availability_dict.get('availability_365', None)

print("Availability for 30 days:", availability_30)
print("Availability for 60 days:", availability_60)
print("Availability for 90 days:", availability_90)
print("Availability for 365 days:", availability_365)

Availability for 30 days: 28
Availability for 60 days: 47
Availability for 90 days: 74
Availability for 365 days: 239

In [4]:
import pandas as pd
import json

# Load the CSV file into a DataFrame
df = pd.read_csv("C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv")

# Function to extract availability values from JSON string
def extract_availabilities(avail_str):
    try:
        availability_dict = json.loads(avail_str.replace("'", "\""))
        availability_30 = availability_dict.get('availability_30', None)
        availability_60 = availability_dict.get('availability_60', None)
        availability_90 = availability_dict.get('availability_90', None)
        availability_365 = availability_dict.get('availability_365', None)
        return availability_30, availability_60, availability_90, availability_365
    except Exception as e:
        print(f"Error extracting availabilities: {e}")
        return None, None, None, None

# Apply the function to the 'availability' column and create new columns for each availability
df['availability_30'], df['availability_60'], df['availability_90'], df['availability_365'] = zip(*df['availability'].map(extract_availabilities))

# Print the DataFrame with the extracted availabilities
print(df[['availability_30', 'availability_60', 'availability_90', 'availability_365']])

      availability_30  availability_60  availability_90  availability_365
0                   0                0                0                 0
1                  30               31               31               243
2                  28               47               74               239
3                   0                0                0                 0
4                   0                0                0                 0
...               ...              ...              ...               ...
5550                0                0                0                 0
5551                0                0                0                 0
5552               29               59               89                89
5553                0                0                0                 0
5554               30               60               90               365

[5555 rows x 4 columns]

In [6]:
# Get unique property types
property_types = df['property_type'].unique()
print(property_types,len(property_types))

['Apartment' 'House' 'Condominium' 'Loft' 'Hostel' 'Guesthouse'
 'Bed and breakfast' 'Serviced apartment' 'Treehouse' 'Bungalow'
 'Guest suite' 'Villa' 'Cabin' 'Townhouse' 'Boutique hotel' 'Boat'
 'Farm stay' 'Cottage' 'Other' 'Earth house' 'Chalet' 'Aparthotel'
 'Resort' 'Tiny house' 'Casa particular (Cuba)' 'Hotel' 'Barn' 'Camper/RV'
 'Nature lodge' 'Hut' 'Heritage hotel (India)' 'Pension (South Korea)'
 'Campsite' 'Houseboat' 'Castle' 'Train'] 36

In [7]:
df['calendar_last_scraped'].unique()

array(['2019-03-11 04:00:00', '2019-03-07 05:00:00',
       '2019-02-16 05:00:00', '2019-03-06 05:00:00',
       '2019-02-11 05:00:00', '2019-02-18 05:00:00',
       '2019-03-08 05:00:00'], dtype=object)

In [2]:
df['last_scraped'].unique()

array(['2019-03-11 04:00:00', '2019-03-07 05:00:00',
       '2019-02-16 05:00:00', '2019-03-06 05:00:00',
       '2019-02-11 05:00:00', '2019-02-18 05:00:00',
       '2019-03-08 05:00:00'], dtype=object)

In [3]:
df['calendar_last_scraped'].isna().sum()

0

In [4]:
df['last_scraped'].isna().sum()

0

In [2]:
df['availability'].unique()

array(["{'availability_30': 0, 'availability_60': 0, 'availability_90': 0, 'availability_365': 0}",
       "{'availability_30': 30, 'availability_60': 31, 'availability_90': 31, 'availability_365': 243}",
       "{'availability_30': 28, 'availability_60': 47, 'availability_90': 74, 'availability_365': 239}",
       ...,
       "{'availability_30': 0, 'availability_60': 0, 'availability_90': 0, 'availability_365': 187}",
       "{'availability_30': 21, 'availability_60': 23, 'availability_90': 25, 'availability_365': 139}",
       "{'availability_30': 23, 'availability_60': 50, 'availability_90': 80, 'availability_365': 261}"],
      dtype=object)

In [3]:
len(df['availability'].unique())

2871

In [2]:
# Extract location information
df['suburb'] = df['address'].apply(lambda x: x.get('suburb', None))

AttributeError: 'str' object has no attribute 'get'

In [3]:
df['government_area'] = df['address'].apply(lambda x: x.get('government_area', None))

AttributeError: 'str' object has no attribute 'get'

In [4]:
import pandas as pd
import json

# Read the CSV file
df = pd.read_csv("C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv")

# Function to safely convert string to dictionary
def parse_address(address):
    try:
        return json.loads(address.replace("'", '"'))
    except (json.JSONDecodeError, AttributeError):
        return {}

# Convert 'address' column from string to dictionary
df['address'] = df['address'].apply(parse_address)

# Access 'suburb' and 'government_area' values
suburb_values = df['address'].apply(lambda x: x.get('suburb', None))
government_area_values = df['address'].apply(lambda x: x.get('government_area', None))

print(suburb_values)
print(government_area_values)

0       None
1       None
2       None
3       None
4       None
        ...
5550    None
5551    None
5552    None
5553    None
5554    None
Name: address, Length: 5555, dtype: object
0       None
1       None
2       None
3       None
4       None
        ...
5550    None
5551    None
5552    None
5553    None
5554    None
Name: address, Length: 5555, dtype: object

In [6]:
import pandas as pd
import re

# Read the CSV file
df = pd.read_csv("C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv")

# Define a function to extract 'suburb' and 'government_area' values using regular expressions
def extract_suburb_and_government_area(address_str):
    try:
        # Define the pattern to match the suburb and government_area values
        pattern = r'"suburb":\s*"([^"]+)",\s*"government_area":\s*"([^"]+)"'
        match = re.search(pattern, address_str)
        if match:
            return match.group(1), match.group(2)
        else:
            return None, None
    except AttributeError:
        return None, None

# Apply the function to extract 'suburb' and 'government_area' values
df['suburb'], df['government_area'] = zip(*df['address'].apply(extract_suburb_and_government_area))

# Display the values
print(df['suburb'])
print(df['government_area'])

0       None
1       None
2       None
3       None
4       None
        ...
5550    None
5551    None
5552    None
5553    None
5554    None
Name: suburb, Length: 5555, dtype: object
0       None
1       None
2       None
3       None
4       None
        ...
5550    None
5551    None
5552    None
5553    None
5554    None
Name: government_area, Length: 5555, dtype: object

In [7]:
import pandas as pd
import ast

# Read the CSV file
df = pd.read_csv("C:\\Users\\user\\Desktop\\airbnb\\abnb_dataset.csv")

# Define a function to extract 'suburb' and 'government_area' values
def extract_suburb_and_government_area(address_str):
    try:
        address_dict = ast.literal_eval(address_str)
        suburb = address_dict.get('suburb', None)
        government_area = address_dict.get('government_area', None)
        return suburb, government_area
    except (ValueError, SyntaxError):
        return None, None

# Apply the function to extract 'suburb' and 'government_area' values
df['suburb'], df['government_area'] = zip(*df['address'].apply(extract_suburb_and_government_area))

# Display the values
print(df['suburb'])
print(df['government_area'])

0                         Mile End
1                       Greenpoint
2
3       Central & Western District
4            Le Plateau-Mont-Royal
                   ...
5550
5551               Jardim Botânico
5552             Downtown Montreal
5553                          Lapa
5554                        Tijuca
Name: suburb, Length: 5555, dtype: object
0                                   Le Plateau-Mont-Royal
1                                              Greenpoint
2       Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...
3                                       Central & Western
4                                   Le Plateau-Mont-Royal
                              ...
5550                                            Pittwater
5551                                      Jardim Botânico
5552                                          Ville-Marie
5553                                               Centro
5554                                         Rio Comprido
Name: government_area, Length: 5555, dtype: object

In [2]:
import pandas as pd

# Load the CSV file into a DataFrame
file_path = "C:\\Users\\user\\Downloads\\airbnb_prices_Montreal.csv"
df = pd.read_csv(file_path)
df

Empty DataFrame
Columns: [U3VidXJiLEF2ZXJhZ2UgUHJpY2UsbGF0aXR1ZGUsbG9uZ2l0dWRlDQpSaXZpw6hyZS1kZXMtUHJhaXJpZXMtUG9pbnRlLWF1eC1UcmVtYmxlcywxNzQ2LjAsNDUuNjUzMTEsLTczLjU2MTI2DQpDaGluYXRvd24sMjUwLjAsNDUuNTA1MDQsLTczLjU2Mzk3DQpNb250LVJveWFsLDE5NS4wLDQ1LjUxNjksLTczLjY1NjM3DQpNb250csOpYWwtT3Vlc3QsMTg5LjAsNDUuNDU1NTgsLTczLjY1NjQ3DQpMYWNoaW5lLDE1OS4wLDQ1LjQ0NDIzLC03My42OTI3NQ0KT2xkIFJvc2Vtb250LDE1Ni4wLDQ1LjU1MTc5LC03My41OTE3OA0KT2xkIE1vbnRyZWFsLDE0OS4wLDQ1LjUwNDg4LC03My41NTU5MQ0KTWlsZSBFbmQsMTQ4LjY2NjY2NjY2NjY2NjY2LDQ1LjUxODg5LC03My41OTExMQ0KTm90cmUtRGFtZS1kZS1HcmFjZSwxMzYuNjY2NjY2NjY2NjY2NjYsNDUuNDc2NDEsLTczLjYxMzU1DQpMYVNhbGxlLDExMC4wLDQ1LjQyODk1LC03My42NTY0OQ0KRG93bnRvd24gTW9udHJlYWwsOTkuMDI3MDI3MDI3MDI3MDMsNDUuNTE2MjUsLTczLjU1NDk1DQpMZSBQbGF0ZWF1LDkzLjUsNDUuNTM0ODEsLTczLjU1OTg1DQpWaWxsZXJheSw5MS43NSw0NS41MzcyNCwtNzMuNjIxNzYNClJvc2Vtb250LUxhIFBldGl0ZS1QYXRyaWUsOTEuMiw0NS41NDkwNCwtNzMuNTgyNA0KTGUgUGxhdGVhdS1Nb250LVJveWFsLDg3LjUyNjMxNTc4OTQ3MzY4LDQ1LjUyMjMzLC03My41NzM4Mw0KTWVyY2llci1Ib2NoZWxhZ2EtTWFpc29ubmV1dmUsODUuODg4ODg4ODg4ODg4ODksNDUuNTg2MDMsLTczLjUyOTg1DQpBaHVudHNpYy1DYXJ0aWVydmlsbGUsODUuMCw0NS41NTE3NCwtNzMuNjQ5DQpXZXN0bW91bnQsODUuMCw0NS40ODg0OSwtNzMuNjA1Mw0KTWNHaWxsIEdoZXR0byw4NS4wLDQ1LjUwOTY0LC03My41NzYzDQpWZXJkdW4sNzkuNDI4NTcxNDI4NTcxNDMsNDUuNDUwOTEsLTczLjU3MDUxDQpHcmlmZmludG93biw3OS4wLDQ1LjQ5NjY1LC03My41NTg2Mw0KR2F5IFZpbGxhZ2UsNzguMzMzMzMzMzMzMzMzMzMsNDUuNTE4OTEsLTczLjU1ODg5DQpPdXRyZW1vbnQsNzcuNiw0NS41MjA0NSwtNzMuNjA5NTENClF1YXJ0aWVyIGRlcyBTcGVjdGFjbGVzLDczLjY2NjY2NjY2NjY2NjY3LDQ1LjUxNzc4LC03My41NjY0Ng0KT2xkIFBvcnQsNzAuMCw0NS41MDIxMywtNzMuNTU4MTENClZpbGxlcmF5LVNhaW50LU1pY2hlbC1QYXJjLUV4dGVuc2lvbiw2Ny4xNjY2NjY2NjY2NjY2Nyw0NS41NTI2NCwtNzMuNjAzODYNClNhaW50LUhlbnJpLDY1LjAsNDUuNDczNDgsLTczLjU4NjY0DQpDb3RlLWRlcy1OZWlnZXMtTm90cmUtRGFtZS1kZS1HcmFjZSw2NS4wLDQ1LjUwMjg2LC03My42Mjc5Nw0KQW5qb3UsNjAuMCw0NS41OTkzLC03My41NTQ4Ng0KSG9jaGVsYWdhLU1haXNvbm5ldXZlLDU3LjAsNDUuNTQ1NDgsLTczLjU0OTQ5DQpMZSBTdWQtT3Vlc3QsNTQuMCw0NS40NzExNiwtNzMuNTg5DQpQYXJjLUV4dGVuc2lvbiw1MC4wLDQ1LjUyNTc3LC03My42MjcxOQ0KSGVtcHN0ZWFkLDUwLjAsNDUuNDc5NywtNzMuNjMxMzkNCkxhIFBldGl0ZS1QYXRyaWUsNDguMzc1LDQ1LjUzNDE0LC03My42MDM1Mg0KU2FpbnQtTGVvbmFyZCw0Ni4wLDQ1LjU4OTYxLC03My41NzcyNQ0KQ290ZS1kZXMtTmVpZ2VzLDI3LjAsNDUuNDg5ODEsLTczLjYzNTk4DQpNb250csOpYWwtRXN0LDE5LjAsNDUuNjA5ODIsLTczLjUxMDM4DQo=]
Index: []